# Generated by Django 5.2.9 on 2025-12-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Detailed description of the task'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('IN_PROGRESS', 'In Progress'),
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        default='PENDING',
                        help_text='Current task status',
                        max_length=20,
                    ),
                ),
                (
                    'priority',
                    models.IntegerField(
                        default=0, help_text='Task priority (higher = more important)'
                    ),
                ),
                (
                    'due_date',
                    models.DateTimeField(blank=True, help_text='Task due date', null=True),
                ),
                (
                    'completed_at',
                    models.DateTimeField(
                        blank=True, help_text='When the task was completed', null=True
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, help_text='When the task was created'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, help_text='When the task was last updated'),
                ),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', '-created_at'],
                'indexes': [
                    models.Index(
                        fields=['status', '-created_at'], name='core_task_status_ec40ea_idx'
                    ),
                    models.Index(fields=['-priority'], name='core_task_priorit_a789c6_idx'),
                ],
            },
        ),
    ]
